### ISSUE TITLE
Предложение по доработке проекта

### ISSUE THREAD

**Issue by YurevichVlada** [StuckInTheCode/I_have_a_plan#2]
На данный момент приложение выполняет основные функции. Как пользователю хотелось бы добавить больше ярких цветов в интерфейс, хотя все элементы хорошо отличимы, это сделала бы его более приятным. Так же хочу предложить возможность добавления рускоязычной версии.

**Comment by StuckInTheCode** [comment]
Спасибо за предложение!
Все пожелания будут учтены в дальнейшем при разработке программы.
